<?php

/* 
 * Role Manager On Screen Help class
 * 
 */

class RM_Screen_Help_Mn {

    public function __construct() {
        
        add_filter('rm_get_settings_general_tab_help', array($this, 'get_settings_general_tab'));
        add_filter('rm_get_settings_additional_modules_tab_help', array($this, 'get_settings_additional_modules_tab'));
        //add_filter('rm_get_settings_default_roles_tab_help', array($this, 'get_settings_default_roles_tab'));
        add_filter('rm_get_settings_multisite_tab_help', array($this, 'get_settings_multisite_tab'));
    }
    // end of __construct()
    
    
    public function get_settings_general_tab($text) {
    
        $text .= '
            <li><strong>'. esc_html__('Show plugins/designs notices to admin only', 'role-manager'). '</strong> - '.
            esc_html__('Show update or install notices generated by plugins or designs to the users with "install_plugins" capability only', 'role-manager') .'</li>
            <li><strong>'. esc_html__('Download jQuery UI CSS from jQuery CDN', 'role-manager'). '</strong> - '.
            esc_html__('Download jQuery UI CSS from jQuery CDN instead of local copy included into the Mtaandao Role Manager installation package', 'role-manager') .'</li>
            <li><strong>'. esc_html__('Role Manager full access capability', 'role-manager'). '</strong> - '.
                esc_html__('if it is empty, then default rule is in action: user should have "administrator" role - '.
                           'for single site Mtaandao installation, "manage_network_users" capability or be the "super administrator" - for multisite one. '.
                           'Input here your own user capability to change this logic.','role-manager') . '</li>            
            <li><strong>' . esc_html__('License key', 'role-manager') .'</strong> - ' .
                   'Input here the license key taken from your mtaandao.co.ke member account. This will turn on automatic updates for the Mtaandao Role Manager. '.
                   'It will get information about available updates from mtaandao.co.ke directly and report about them the same way as any other plugin '.
                   'from the mtaandao.co.ke plugins repository does.</li>';
        
        return $text;
    }
    // end of get_settings_general_tab()
    
   
    public function get_settings_additional_modules_tab($text) {
        $text .= '<li><strong>' . esc_html__('Activate "Administrator Menu Access" module', 'role-manager'). '</strong> - ' .
                esc_html__('Adds "Admin Menu" button to the "Role Manager" page. Turning on checkboxes near menu items in the opened dialog window you may '.
                'block admin menu items available for the selected role', 'role-manager') . 
                ' (<a href="https://www.mtaandao.co.ke/block-admin-menu-items">'. esc_html__('more info...', 'role-manager') .'</a>)</li>'.
                '<li><strong>' . esc_html__('Activate "Widgets Access" module', 'role-manager'). '</strong> - ' .
                esc_html__('Adds "Widgets" button to the "Role Manager" page. Turning on checkboxes near widgets names in the opened dialog window you may '.
                'block widgets available for selected role under the "Appearance" menu', 'role-manager') . 
                ' (<a href="https://www.mtaandao.co.ke/block-selected-widgets-under-appearance-menu">'. esc_html__('more info...', 'role-manager') .'</a>)</li>'.
                '<li><strong>' . esc_html__('Activate "Metaboxes Access" module', 'role-manager'). '</strong> - ' .
                esc_html__('Adds "Metaboxes" button to the "Role Manager" page. Turning on checkboxes to the left from the meta boxes names in the opened dialog window you may '.
                'block meta boxes available for selected role', 'role-manager') . 
                ' (<a href="https://www.mtaandao.co.ke/block-selected-meta-boxes">'. esc_html__('more info...', 'role-manager') .'</a>)</li>'.
                '<li><strong>' . esc_html__('Activate "Other Roles Access" module', 'role-manager') .'</strong> - ' .
                esc_html__('Adds "Other Roles" button to the "Role Manager" page. Turning on checkboxes near roles names in the opened dialog window you may '.
                'block that roles from selection in the Mtaandao drop-down lists (e.g "Role" at the user profile page) '.
                'by the user with current role. Users with blocked roles will not be available for view/edit at the “Users” page also.', 'role-manager') . 
                ' (<a href="https://www.mtaandao.co.ke/other-roles-access/">'. esc_html__('more info...', 'role-manager') .'</a>)</li>'.
                '<li><strong>' . esc_html__('Activate per plugin user access management for plugins activation', 'role-manager'). '</strong> - '.
                esc_html__('this featrm is useful when you need to allow different users activate/deactivate different plugins. '.
                'When this option is turned on you may input, what plugins are available for the user with "activate_plugins" capability. ' .
                'Go to such user profile and select plugins you allow him to manage.', 'role-manager') . '</li>'.
                '<li><strong>' . esc_html__('Activate "Create Post/Page" capability', 'role-manager'). '</strong> - ' .
                esc_html__('Turning on this option you automatically add "create_posts" and "create_pages" '.
                'capabilities to the list of Mtaandao core user capabilities. After that user with "edit_posts" capability '.
                '(even administrator) will can not create new post or page until you apparently include this capability '. 
                'to his user role. "edit_posts" will permit just to edit posts. Go to "Role Manager" and turn on "create_posts", "create_pages" capability" '.
                'for "Administrator" role and other roles of your choice after this option activation.', 'role-manager') . '</li>
                 <li><strong>' . esc_html__('Activate user access management to editing selected posts and pages', 'role-manager'). '</strong> - ' .
                esc_html__('This way you may have for example the user with limited "Editor" role, who may edit just 2-3 posts or pages, but has no access '.
                'to all the rest. After this option activation go to the user profile and input allowed posts/pages ID '.
                'to the correspondent text input field. That\'s it.', 'role-manager') . 
                ' (<a href="https://www.mtaandao.co.ke/allow-user-edit-selected-posts">'. esc_html__('more info...', 'role-manager') .'</a>)</li>'.
                '<li><strong>' . esc_html__('Force custom post types to use their own capabilities', 'role-manager'). '</strong> - ' .
                esc_html__('Some custom post types use Mtaandao built-in "posts" based capabilities set: "edit_posts", "delete_posts", etc. '.
                'Activating this option your force such custom post types to use their own capabilities set, based on custom post type name: '.
                'for "videos" custom post type it will be "edit_videos", "delete_videos", etc.', 'role-manager');
        if (class_exists('GFForms')) {
            $text .=         
                '<li><strong>' . esc_html__('Activate per form user access management for Gravity Forms', 'role-manager'). '</strong> - ' .
                esc_html__('after turning on this option you may see the new “Gravity Forms Restrictions” section at the user profile '.
                'with input field “Allow access to forms with ID (comma separated)”. This field will appear at profile '.
                'of those users only who have at least one capability from the “Gravity Forms” capabilities list, '.
                'e.g. “gravityforms_edit_forms”, “gravityforms_view_entries”, etc. Look ', 'role-manager') .
                '<a href="http://mtaandao.co.ke/restrict-users-access-gravity-forms/">'.
                esc_html__('support video', 'role-manager'). '</a> ' . 
                esc_html__('for your reference.', 'role-manager') . '</li>';
        }
        $text .= 
                '<li><strong>' . esc_html__('Activate [role_manager roles="role1, role2, ..."] shortcode:', 'role-manager') .'</strong> - '.
                esc_html__('Allows view the content enclosed inside [role_manager roles="role1, role2"] Some restricted content [/role-manager] '.
                'just to users who have one of roles listed in the "roles" attribute. "role1" or "role2" in this case. '. 
                'Other users (except administrator) will not see the "restricted content" at the post or page. '.
                'When this option is turned off, all restricted content input earlier, becomes available as usual content.', 'role-manager').'</li>'.
                 '<li><strong>' . esc_html__('Activate content view restrictions', 'role-manager') .'</strong> - '.
                esc_html__('Allows to set which roles may or prohibited view what post/page, custom post type', 'role-manager') .
                ' (<a href="https://www.mtaandao.co.ke/content-view-access-restriction-selected-roles/">'. esc_html__('more info...', 'role-manager') .'</a>)</li>';    
                                          
        return $text;
    }
    // end of get_settings_additional_modules_tab()
    
    
    public function get_settings_default_roles_tab($text) {
        
        return $text;
    }
    // end of get_settings_default_roles_tab()
    
    
    public function get_settings_multisite_tab($text) {
        
        $text .= '<li><strong>' . esc_html__('Allow single site administrator access to Role Manager', 'role-manager') . '</strong> - '.
            esc_html__('Super administator only has access to the Role Manager under multi-site Mtaandao installation by default.' .
            'Turn on this option if you wish to make Role Manager available for subsite administrators .', 'role-manager') . '</li>
            <li><strong>' . esc_html__('Show help links for single site administrator', 'role-manager') .'</strong> - '.
            esc_html__('Turning off this checkbox you will hide question side icons to the right of '.
            'user capabilities at the Role Manager.', 'role-manager') .'</li>
            <li><span style="color: red; font-weight: bold;">' . esc_html__('Enable "unfiltered_html" capability', 'role-manager') .'</span> - '.
            esc_html__('Mtaandao multisite blocks this capabilities by default for all users except superadmin. '.
            'Be careful and double think before enable it. This makes your site potentially vulnerable.', 'role-manager'). '
            <li><strong>' . esc_html__('Activate access management for designs', 'role-manager') .'</strong> - '.
            esc_html__('with this option active you may setup individual lists of designs available for activation '. 
            'to selected single sites administrators ', 'role-manager') .'</li>
            <li><strong>' . esc_html__('Activate access restrictions to Role Manager for single site administrator', 'role-manager') .'</strong> - '.
            esc_html__('Restrict access of single sites administrators to the selected user capabilities and '. 
            'Add/Delete role operations inside Role Manager','role-manager') .'</li>';            
                
        return $text;
    }
    // end of get_settings_multisite_tab()
    
}
// end of RM_Screen_Help_Mn
